name: Orury CD with Gradle

env:
  PROJECT_NAME: orury
  BUCKET_NAME: orury-bepo-bucket
  CODE_DEPLOY_APP_NAME: orury-code-deploy
  DEPLOYMENT_GROUP_NAME: orury-code-deploy-group
  DOCKER_ENV: .env
  PROD_PORT: 8085
  DEV_PORT: 8087

on:
  push:
    branches: [ "main", "feature/#271_setting_auto_deploy" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make application.properties
        run: |
          touch ./orury-client/src/main/resources/application-secret.properties
          touch ./orury-batch/src/main/resources/application-secret.properties
          echo "${{ secrets.APPLICATION_SECRET }}" > ./orury-client/src/main/resources/application-secret.properties
          echo "${{ secrets.APPLICATION_SECRET }}" > ./orury-batch/src/main/resources/application-secret.properties
          cat ./orury-client/src/main/resources/application-secret.properties
          cat ./orury-batch/src/main/resources/application-secret.properties

      - name: Make env file
        run: |
          touch ./.env
          echo "${{ secrets.DOCKER_ENV }}" >> ./.env
          cat ./.env

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            -Dspring.profiles.active=prod
            ./gradlew build -Pprod
          else
            -Dspring.profiles.active=dev
            ./gradlew build -Pdev
          fi
        shell: bash

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --application-name $CODE_DEPLOY_APP_NAME \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name $DEPLOYMENT_GROUP_NAME \
          --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip